export const TOUR_TARGETS = {
  SIDEBAR: 'tour-sidebar',
  SIDEBAR_TOGGLE: 'tour-sidebar-toggle',
  SIDEBAR_SEARCH: 'tour-sidebar-search',
  MEETING_LIST: 'tour-meeting-list',
  SIDEBAR_ACTIONS: 'tour-sidebar-actions',
  MAIN_CONTENT: 'tour-main-content',
  RECORDING_CONTROLS: 'tour-recording-controls',
  USER_GUIDE_BUTTON: 'tour-user-guide-button',
  SETTINGS_SIDEBAR_BUTTON: 'tour-settings-sidebar-button',
  SETTINGS_TAB_GENERAL: 'tour-settings-tab-general',
  SETTINGS_TAB_SUMMARY: 'tour-settings-tab-summary',
  SETTINGS_TAB_TEMPLATES: 'tour-settings-tab-templates',
  SETTINGS_SELECT_FOLDER: 'tour-settings-select-folder',
  SETTINGS_OPEN_FOLDER: 'tour-settings-open-folder',
  SETTINGS_AUTO_SAVE: 'tour-settings-auto-save',
  SETTINGS_DEVICES: 'tour-settings-devices',
  SETTINGS_AUTO_SUMMARY: 'tour-settings-auto-summary',
  SETTINGS_TEMPLATE_ITEM: 'tour-settings-template-item',
  SETTINGS_TEMPLATE_SET_DEFAULT: 'tour-settings-template-set-default',
  TEMPLATE_CREATE: 'tour-template-create',
  TEMPLATE_NAME: 'tour-template-name',
  TEMPLATE_DESCRIPTION: 'tour-template-description',
  TEMPLATE_SECTION_FIRST: 'tour-template-section-first',
  TEMPLATE_SECTION_TITLE: 'tour-template-section-title',
  TEMPLATE_SECTION_INSTRUCTION: 'tour-template-section-instruction',
  TEMPLATE_SECTION_FORMAT: 'tour-template-section-format',
  TEMPLATE_ADD_SECTION: 'tour-template-add-section',
  TEMPLATE_SECTION_SECOND: 'tour-template-section-second',
  TEMPLATE_SAVE_NEW: 'tour-template-save-new',
  TEMPLATE_BACK: 'tour-template-back',
  TEMPLATE_BUILTIN_ACT: 'tour-template-builtin-act',
  TEMPLATE_CLONE: 'tour-template-clone',
  TEMPLATE_CLONED_ITEM: 'tour-template-cloned-item',
  SETTINGS_TAB_PROMPT: 'tour-settings-tab-prompt',
  PROMPT_EDITOR: 'tour-prompt-editor',
  PROMPT_HEADER: 'tour-prompt-header',
} as const;

export function tourTargetSelector(target: (typeof TOUR_TARGETS)[keyof typeof TOUR_TARGETS]) {
  return `[data-tour="${target}"]`;
}
