[workspace]
resolver = "2"
members = [
    "frontend/src-tauri"
]

# Shared workspace settings
[workspace.package]
edition = "2021"
rust-version = "1.77"

[patch.crates-io]
cpal = { git = "https://github.com/RustAudio/cpal", rev = "51c3b43" }
esaxx-rs = { git = "https://github.com/ocentra/esaxx-rs.git", rev = "4f4fd5acd624e43c770a0d198fcaa9d97bfd7f0b" }
