// Mã ISO 639-1 — nhãn hiển thị tiếng Việt cho giao diện
export interface Language {
  code: string;
  name: string;
}

export const LANGUAGES: Language[] = [
  { code: 'auto', name: 'Tự động (ngôn ngữ gốc)' },
  { code: 'auto-translate', name: 'Tự động (dịch sang tiếng Anh)' },
  { code: 'en', name: 'Tiếng Anh' },
  { code: 'zh', name: 'Tiếng Trung' },
  { code: 'de', name: 'Tiếng Đức' },
  { code: 'es', name: 'Tiếng Tây Ban Nha' },
  { code: 'ru', name: 'Tiếng Nga' },
  { code: 'ko', name: 'Tiếng Hàn' },
  { code: 'fr', name: 'Tiếng Pháp' },
  { code: 'ja', name: 'Tiếng Nhật' },
  { code: 'pt', name: 'Tiếng Bồ Đào Nha' },
  { code: 'tr', name: 'Tiếng Thổ Nhĩ Kỳ' },
  { code: 'pl', name: 'Tiếng Ba Lan' },
  { code: 'ca', name: 'Tiếng Catalan' },
  { code: 'nl', name: 'Tiếng Hà Lan' },
  { code: 'ar', name: 'Tiếng Ả Rập' },
  { code: 'sv', name: 'Tiếng Thụy Điển' },
  { code: 'it', name: 'Tiếng Ý' },
  { code: 'id', name: 'Tiếng Indonesia' },
  { code: 'hi', name: 'Tiếng Hindi' },
  { code: 'fi', name: 'Tiếng Phần Lan' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'he', name: 'Tiếng Do Thái' },
  { code: 'uk', name: 'Tiếng Ukraina' },
  { code: 'el', name: 'Tiếng Hy Lạp' },
  { code: 'ms', name: 'Tiếng Mã Lai' },
  { code: 'cs', name: 'Tiếng Séc' },
  { code: 'ro', name: 'Tiếng Romania' },
  { code: 'da', name: 'Tiếng Đan Mạch' },
  { code: 'hu', name: 'Tiếng Hungary' },
  { code: 'ta', name: 'Tiếng Tamil' },
  { code: 'no', name: 'Tiếng Na Uy (Bokmål)' },
  { code: 'th', name: 'Tiếng Thái' },
  { code: 'ur', name: 'Tiếng Urdu' },
  { code: 'hr', name: 'Tiếng Croatia' },
  { code: 'bg', name: 'Tiếng Bulgaria' },
  { code: 'lt', name: 'Tiếng Litva' },
  { code: 'la', name: 'Tiếng Latinh' },
  { code: 'mi', name: 'Tiếng Maori' },
  { code: 'ml', name: 'Tiếng Malayalam' },
  { code: 'cy', name: 'Tiếng Wales' },
  { code: 'sk', name: 'Tiếng Slovakia' },
  { code: 'te', name: 'Tiếng Telugu' },
  { code: 'fa', name: 'Tiếng Ba Tư' },
  { code: 'lv', name: 'Tiếng Latvia' },
  { code: 'bn', name: 'Tiếng Bengal' },
  { code: 'sr', name: 'Tiếng Serbia' },
  { code: 'az', name: 'Tiếng Azerbaijan' },
  { code: 'sl', name: 'Tiếng Slovenia' },
  { code: 'kn', name: 'Tiếng Kannada' },
  { code: 'et', name: 'Tiếng Estonia' },
  { code: 'mk', name: 'Tiếng Macedonia' },
  { code: 'br', name: 'Tiếng Breton' },
  { code: 'eu', name: 'Tiếng Basque' },
  { code: 'is', name: 'Tiếng Iceland' },
  { code: 'hy', name: 'Tiếng Armenia' },
  { code: 'ne', name: 'Tiếng Nepal' },
  { code: 'mn', name: 'Tiếng Mông Cổ' },
  { code: 'bs', name: 'Tiếng Bosnia' },
  { code: 'kk', name: 'Tiếng Kazakhstan' },
  { code: 'sq', name: 'Tiếng Albania' },
  { code: 'sw', name: 'Tiếng Swahili' },
  { code: 'gl', name: 'Tiếng Galicia' },
  { code: 'mr', name: 'Tiếng Marathi' },
  { code: 'pa', name: 'Tiếng Punjab' },
  { code: 'si', name: 'Tiếng Sinhala' },
  { code: 'km', name: 'Tiếng Khmer' },
  { code: 'sn', name: 'Tiếng Shona' },
  { code: 'yo', name: 'Tiếng Yoruba' },
  { code: 'so', name: 'Tiếng Somali' },
  { code: 'af', name: 'Tiếng Afrikaans' },
  { code: 'oc', name: 'Tiếng Occitan' },
  { code: 'ka', name: 'Tiếng Georgia' },
  { code: 'be', name: 'Tiếng Belarus' },
  { code: 'tg', name: 'Tiếng Tajik' },
  { code: 'sd', name: 'Tiếng Sindhi' },
  { code: 'gu', name: 'Tiếng Gujarati' },
  { code: 'am', name: 'Tiếng Amharic' },
  { code: 'yi', name: 'Tiếng Yiddish' },
  { code: 'lo', name: 'Tiếng Lào' },
  { code: 'uz', name: 'Tiếng Uzbek' },
  { code: 'fo', name: 'Tiếng Faroe' },
  { code: 'ht', name: 'Tiếng Haiti (Creole)' },
  { code: 'ps', name: 'Tiếng Pashto' },
  { code: 'tk', name: 'Tiếng Turkmen' },
  { code: 'nn', name: 'Tiếng Na Uy (Nynorsk)' },
  { code: 'mt', name: 'Tiếng Malta' },
  { code: 'sa', name: 'Tiếng Phạn (Sanskrit)' },
  { code: 'lb', name: 'Tiếng Luxembourg' },
  { code: 'my', name: 'Tiếng Myanmar' },
  { code: 'bo', name: 'Tiếng Tây Tạng' },
  { code: 'tl', name: 'Tiếng Tagalog' },
  { code: 'mg', name: 'Tiếng Malagasy' },
  { code: 'as', name: 'Tiếng Assam' },
  { code: 'tt', name: 'Tiếng Tatar' },
  { code: 'haw', name: 'Tiếng Hawaii' },
  { code: 'ln', name: 'Tiếng Lingala' },
  { code: 'ha', name: 'Tiếng Hausa' },
  { code: 'ba', name: 'Tiếng Bashkir' },
  { code: 'jw', name: 'Tiếng Java' },
  { code: 'su', name: 'Tiếng Sunda' },
];
